### ISSUE TITLE
Search result is empty dataframe. Any fallback file?

### ISSUE THREAD

**Issue by githarb** [stanford-esrg/LEO_HitchHiking#1]
I run `python main.py` and get `KeyError: "None of [Index(['ip'], dtype='object')] are in the [columns]"` as output. According to `data_collection.py` a fallback file can be used. I wonder if there is any?
~~~python
# Uncomment the following block if using a fallback file incase Censys queries
# fail. 
# If the provided dataframe does not contain data, use a fallback file

# if df.empty:
#     print("(paris_traceroute_exposed_services) using fallback file")
#     df = pd.read_json(
#         'MYFALLBACKFILE.json' # TODO: edit to fallback file path
#         lines=True
#     )
#     df = df[['ip', 'date', 'asn', 'dns_name', 'port', 'pep_link']]
#     fallback_file = True

**Comment by mandatran** [comment]
You can create a fallback file by running `get_censys_exposed_services` and saving the returned dataframe as a json file. To query Censys you will need to create a Censys account and configure your credentials following the setup guide here: https://github.com/censys/censys-python .
