### ISSUE TITLE
How to get permission to Google BigQuery tables?

### ISSUE THREAD

**Issue by govwin** [stanford-esrg/LEO_HitchHiking#2]
Here is the error when I try to query the data with "SELECT 1 FROM `satellite-measurement-386900.starlink.leo_hitchhiking_latency` LIMIT 1000" 
Access Denied: Table satellite-measurement-386900:starlink_endpoint_pings.*: User does not have permission to query table satellite-measurement-386900:starlink_endpoint_pings.*, or perhaps it does not exist in location US.

**Comment by LizIzhikevich** [comment]
Hello! I think I fixed the permission error on the table, could you try now?

**Comment by govwin** [comment]
Thanks a lot. Query works now.
